openapi: 3.2.0
info:
  version: '2018-09-22'
  x-release: v4
  title: CodeArtifact Domain API
  description: CodeArtifact is a fully managed artifact repository compatible with language-native package managers and build tools such as npm, Apache Maven, pip, and dotnet.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codeartifact
  x-aws-signingName: codeartifact
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codeartifact-2018-09-22.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codeartifact.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeArtifact multi-region endpoint
- url: https://codeartifact.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeArtifact multi-region endpoint
- url: http://codeartifact.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeArtifact endpoint for China (Beijing) and China (Ningxia)
- url: https://codeartifact.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeArtifact endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Domain
paths:
  /v1/domain#domain:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateDomain
      description: 'Creates a domain. CodeArtifact domains make it easier to manage multiple repositories across an organization. You can use a domain to apply permissions across many repositories owned by different Amazon Web Services accounts. An asset is stored only once in a domain, even if it''s in multiple repositories.


        Although you can have multiple domains, we recommend a single production domain that contains all published artifacts so that your development teams can find and share packages. You can use a second pre-production domain to test changes to the production domain configuration.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDomainResult'
              examples:
                CreateDomain200Example:
                  summary: Default CreateDomain 200 response
                  x-microcks-default: true
                  value:
                    domain: my-domain
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                CreateDomain480Example:
                  summary: Default CreateDomain 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                CreateDomain481Example:
                  summary: Default CreateDomain 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                CreateDomain482Example:
                  summary: Default CreateDomain 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                CreateDomain483Example:
                  summary: Default CreateDomain 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ServiceQuotaExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
              examples:
                CreateDomain484Example:
                  summary: Default CreateDomain 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                CreateDomain485Example:
                  summary: Default CreateDomain 485 response
                  x-microcks-default: true
                  value: example-value
        '486':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                CreateDomain486Example:
                  summary: Default CreateDomain 486 response
                  x-microcks-default: true
                  value: '500123'
      parameters:
      - name: domain
        in: query
        required: true
        description: ' The name of the domain to create. All domain names in an Amazon Web Services Region that are in the same Amazon Web Services account must be unique. The domain name is used as the prefix in DNS hostnames. Do not use sensitive information in a domain name because it is publicly discoverable. '
        schema:
          type: string
          pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
          minLength: 2
          maxLength: 50
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                encryptionKey:
                  description: <p> The encryption key for the domain. This is used to encrypt content stored in a domain. An encryption key can be a key ID, a key Amazon Resource Name (ARN), a key alias, or a key alias ARN. To specify an <code>encryptionKey</code>, your IAM role must have <code>kms:DescribeKey</code> and <code>kms:CreateGrant</code> permissions on the encryption key that is used. For more information, see <a href="https://docs.aws.amazon.com/kms/latest/APIReference/API_DescribeKey.html#API_DescribeKey_RequestSyntax">DescribeKey</a> in the <i>Key Management Service API Reference</i> and <a href="https://docs.aws.amazon.com/kms/latest/developerguide/kms-api-permissions-reference.html">Key Management Service API Permissions Reference</a> in the <i>Key Management Service Developer Guide</i>. </p> <important> <p> CodeArtifact supports only symmetric CMKs. Do not associate an asymmetric CMK with your domain. For more information, see <a href="https://docs.aws.amazon.com/kms/latest/developerguide/symmetric-asymmetric.html">Using symmetric and asymmetric keys</a> in the <i>Key Management Service Developer Guide</i>. </p> </important>
                  type: string
                  pattern: \S+
                  minLength: 1
                  maxLength: 1011
                tags:
                  description: One or more tag key-value pairs for the domain.
                  type: array
                  items:
                    $ref: '#/components/schemas/Tag'
                  minItems: 0
                  maxItems: 200
            examples:
              CreateDomainRequestExample:
                summary: Default CreateDomain request
                x-microcks-default: true
                value:
                  encryptionKey: arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012
                  tags:
                  - key: arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012
                    value: example-value
      summary: Amazon CodeArtifact Create Domain
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Domain
    delete:
      operationId: DeleteDomain
      description: Deletes a domain. You cannot delete a domain that contains repositories. If you want to delete a domain with repositories, first delete its repositories.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteDomainResult'
              examples:
                DeleteDomain200Example:
                  summary: Default DeleteDomain 200 response
                  x-microcks-default: true
                  value:
                    domain: my-domain
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                DeleteDomain480Example:
                  summary: Default DeleteDomain 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                DeleteDomain481Example:
                  summary: Default DeleteDomain 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                DeleteDomain482Example:
                  summary: Default DeleteDomain 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                DeleteDomain483Example:
                  summary: Default DeleteDomain 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                DeleteDomain484Example:
                  summary: Default DeleteDomain 484 response
                  x-microcks-default: true
                  value: '500123'
      parameters:
      - name: domain
        in: query
        required: true
        description: ' The name of the domain to delete. '
        schema:
          type: string
          pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
          minLength: 2
          maxLength: 50
      - name: domain-owner
        in: query
        required: false
        description: ' The 12-digit account number of the Amazon Web Services account that owns the domain. It does not include dashes or spaces. '
        schema:
          type: string
          pattern: '[0-9]{12}'
          minLength: 12
          maxLength: 12
      summary: Amazon CodeArtifact Delete Domain
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Domain
    get:
      operationId: DescribeDomain
      description: Returns a DomainDescription object that contains information about the requested domain.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeDomainResult'
              examples:
                DescribeDomain200Example:
                  summary: Default DescribeDomain 200 response
                  x-microcks-default: true
                  value:
                    domain:
                      name: my-package
                      owner: '123456789012'
                      arn: arn:aws:codeartifact:us-east-1:123456789012:domain/my-domain
                      status: Active
                      createdTime: example-value
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                DescribeDomain480Example:
                  summary: Default DescribeDomain 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                DescribeDomain481Example:
                  summary: Default DescribeDomain 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                DescribeDomain482Example:
                  summary: Default DescribeDomain 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                DescribeDomain483Example:
                  summary: Default DescribeDomain 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                DescribeDomain484Example:
                  summary: Default DescribeDomain 484 response
                  x-microcks-default: true
                  value: '500123'
      parameters:
      - name: domain
        in: query
        required: true
        description: ' A string that specifies the name of the requested domain. '
        schema:
          type: string
          pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
          minLength: 2
          maxLength: 50
      - name: domain-owner
        in: query
        required: false
        description: ' The 12-digit account number of the Amazon Web Services account that owns the domain. It does not include dashes or spaces. '
        schema:
          type: string
          pattern: '[0-9]{12}'
          minLength: 12
          maxLength: 12
      summary: Amazon CodeArtifact Describe Domain
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Domain
  /v1/domain/permissions/policy#domain:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    delete:
      operationId: DeleteDomainPermissionsPolicy
      description: Deletes the resource policy set on a domain.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteDomainPermissionsPolicyResult'
              examples:
                DeleteDomainPermissionsPolicy200Example:
                  summary: Default DeleteDomainPermissionsPolicy 200 response
                  x-microcks-default: true
                  value:
                    policy: example-value
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                DeleteDomainPermissionsPolicy480Example:
                  summary: Default DeleteDomainPermissionsPolicy 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                DeleteDomainPermissionsPolicy481Example:
                  summary: Default DeleteDomainPermissionsPolicy 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                DeleteDomainPermissionsPolicy482Example:
                  summary: Default DeleteDomainPermissionsPolicy 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                DeleteDomainPermissionsPolicy483Example:
                  summary: Default DeleteDomainPermissionsPolicy 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                DeleteDomainPermissionsPolicy484Example:
                  summary: Default DeleteDomainPermissionsPolicy 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                DeleteDomainPermissionsPolicy485Example:
                  summary: Default DeleteDomainPermissionsPolicy 485 response
                  x-microcks-default: true
                  value: '500123'
      parameters:
      - name: domain
        in: query
        required: true
        description: ' The name of the domain associated with the resource policy to be deleted. '
        schema:
          type: string
          pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
          minLength: 2
          maxLength: 50
      - name: domain-owner
        in: query
        required: false
        description: ' The 12-digit account number of the Amazon Web Services account that owns the domain. It does not include dashes or spaces. '
        schema:
          type: string
          pattern: '[0-9]{12}'
          minLength: 12
          maxLength: 12
      - name: policy-revision
        in: query
        required: false
        description: ' The current revision of the resource policy to be deleted. This revision is used for optimistic locking, which prevents others from overwriting your changes to the domain''s resource policy. '
        schema:
          type: string
          pattern: \S+
          minLength: 1
          maxLength: 100
      summary: Amazon CodeArtifact Delete Domain Permissions Policy
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Domain
    get:
      operationId: GetDomainPermissionsPolicy
      description: 'Returns the resource policy attached to the specified domain.


        The policy is a resource-based policy, not an identity-based policy. For more information, see Identity-based policies and resource-based policies in the IAM User Guide.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDomainPermissionsPolicyResult'
              examples:
                GetDomainPermissionsPolicy200Example:
                  summary: Default GetDomainPermissionsPolicy 200 response
                  x-microcks-default: true
                  value:
                    policy: example-value
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                GetDomainPermissionsPolicy480Example:
                  summary: Default GetDomainPermissionsPolicy 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                GetDomainPermissionsPolicy481Example:
                  summary: Default GetDomainPermissionsPolicy 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                GetDomainPermissionsPolicy482Example:
                  summary: Default GetDomainPermissionsPolicy 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                GetDomainPermissionsPolicy483Example:
                  summary: Default GetDomainPermissionsPolicy 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                GetDomainPermissionsPolicy484Example:
                  summary: Default GetDomainPermissionsPolicy 484 response
                  x-microcks-default: true
                  value: '500123'
      parameters:
      - name: domain
        in: query
        required: true
        description: ' The name of the domain to which the resource policy is attached. '
        schema:
          type: string
          pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
          minLength: 2
          maxLength: 50
      - name: domain-owner
        in: query
        required: false
        description: ' The 12-digit account number of the Amazon Web Services account that owns the domain. It does not include dashes or spaces. '
        schema:
          type: string
          pattern: '[0-9]{12}'
          minLength: 12
          maxLength: 12
      summary: Amazon CodeArtifact Get Domain Permissions Policy
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Domain
  /v1/domain/repositories#domain:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListRepositoriesInDomain
      description: Returns a list of RepositorySummary objects. Each RepositorySummary contains information about a repository in the specified domain and that matches the input parameters.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRepositoriesInDomainResult'
              examples:
                ListRepositoriesInDomain200Example:
                  summary: Default ListRepositoriesInDomain 200 response
                  x-microcks-default: true
                  value:
                    repositories: my-repo
                    nextToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                ListRepositoriesInDomain480Example:
                  summary: Default ListRepositoriesInDomain 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                ListRepositoriesInDomain481Example:
                  summary: Default ListRepositoriesInDomain 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                ListRepositoriesInDomain482Example:
                  summary: Default ListRepositoriesInDomain 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                ListRepositoriesInDomain483Example:
                  summary: Default ListRepositoriesInDomain 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                ListRepositoriesInDomain484Example:
                  summary: Default ListRepositoriesInDomain 484 response
                  x-microcks-default: true
                  value: '500123'
      parameters:
      - name: domain
        in: query
        required: true
        description: ' The name of the domain that contains the returned list of repositories. '
        schema:
          type: string
          pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
          minLength: 2
          maxLength: 50
      - name: domain-owner
        in: query
        required: false
        description: ' The 12-digit account number of the Amazon Web Services account that owns the domain. It does not include dashes or spaces. '
        schema:
          type: string
          pattern: '[0-9]{12}'
          minLength: 12
          maxLength: 12
      - name: administrator-account
        in: query
        required: false
        description: ' Filter the list of repositories to only include those that are managed by the Amazon Web Services account ID. '
        schema:
          type: string
          pattern: '[0-9]{12}'
          minLength: 12
          maxLength: 12
      - name: repository-prefix
        in: query
        required: false
        description: ' A prefix used to filter returned repositories. Only repositories with names that start with <code>repositoryPrefix</code> are returned. '
        schema:
          type: string
          pattern: '[A-Za-z0-9][A-Za-z0-9._\-]{1,99}'
          minLength: 2
          maxLength: 100
      - name: max-results
        in: query
        required: false
        description: ' The maximum number of results to return per page. '
        schema:
          type: integer
          minimum: 1
          maximum: 1000
      - name: next-token
        in: query
        required: false
        description: ' The token for the next set of results. Use the value returned in the previous response in the next request to retrieve the next set of results. '
        schema:
          type: string
          pattern: \S+
          minLength: 1
          maxLength: 2000
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      summary: Amazon CodeArtifact List Repositories in Domain
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Domain
  /v1/domain/permissions/policy:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    put:
      operationId: PutDomainPermissionsPolicy
      description: 'Sets a resource policy on a domain that specifies permissions to access it.


        When you call PutDomainPermissionsPolicy, the resource policy on the domain is ignored when evaluting permissions. This ensures that the owner of a domain cannot lock themselves out of the domain, which would prevent them from being able to update the resource policy.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutDomainPermissionsPolicyResult'
              examples:
                PutDomainPermissionsPolicy200Example:
                  summary: Default PutDomainPermissionsPolicy 200 response
                  x-microcks-default: true
                  value:
                    policy: example-value
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                PutDomainPermissionsPolicy480Example:
                  summary: Default PutDomainPermissionsPolicy 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                PutDomainPermissionsPolicy481Example:
                  summary: Default PutDomainPermissionsPolicy 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                PutDomainPermissionsPolicy482Example:
                  summary: Default PutDomainPermissionsPolicy 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                PutDomainPermissionsPolicy483Example:
                  summary: Default PutDomainPermissionsPolicy 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ServiceQuotaExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
              examples:
                PutDomainPermissionsPolicy484Example:
                  summary: Default PutDomainPermissionsPolicy 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                PutDomainPermissionsPolicy485Example:
                  summary: Default PutDomainPermissionsPolicy 485 response
                  x-microcks-default: true
                  value: example-value
        '486':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                PutDomainPermissionsPolicy486Example:
                  summary: Default PutDomainPermissionsPolicy 486 response
                  x-microcks-default: true
                  value: '500123'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - domain
              - policyDocument
              properties:
                domain:
                  description: ' The name of the domain on which to set the resource policy. '
                  type: string
                  pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
                  minLength: 2
                  maxLength: 50
                domainOwner:
                  description: ' The 12-digit account number of the Amazon Web Services account that owns the domain. It does not include dashes or spaces. '
                  type: string
                  pattern: '[0-9]{12}'
                  minLength: 12
                  maxLength: 12
                policyRevision:
                  description: ' The current revision of the resource policy to be set. This revision is used for optimistic locking, which prevents others from overwriting your changes to the domain''s resource policy. '
                  type: string
                  pattern: \S+
                  minLength: 1
                  maxLength: 100
                policyDocument:
                  description: ' A valid displayable JSON Aspen policy string to be set as the access control resource policy on the provided domain. '
                  type: string
                  pattern: '[\P{C}\s]+'
                  minLength: 1
                  maxLength: 7168
            examples:
              PutDomainPermissionsPolicyRequestExample:
                summary: Default PutDomainPermissionsPolicy request
                x-microcks-default: true
                value:
                  domain: my-domain
                  domainOwner: my-domain
                  policyRevision: example-value
                  policyDocument: example-value
      summary: Amazon CodeArtifact Put Domain Permissions Policy
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Domain
components:
  schemas:
    TagValue:
      type: string
      pattern: \P{C}*
      minLength: 0
      maxLength: 256
    DomainStatus:
      type: string
      enum:
      - Active
      - Deleted
    ConflictException: {}
    PutDomainPermissionsPolicyResult:
      type: object
      properties:
        policy:
          allOf:
          - $ref: '#/components/schemas/ResourcePolicy'
          - description: ' The resource policy that was set after processing the request. '
    DomainName:
      type: string
      pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
      minLength: 2
      maxLength: 50
    Description:
      type: string
      pattern: \P{C}*
      maxLength: 1000
    ServiceQuotaExceededException: {}
    InternalServerException: {}
    GetDomainPermissionsPolicyResult:
      type: object
      properties:
        policy:
          allOf:
          - $ref: '#/components/schemas/ResourcePolicy'
          - description: ' The returned resource policy. '
    ValidationException: {}
    ThrottlingException: {}
    ResourceNotFoundException: {}
    AccountId:
      type: string
      pattern: '[0-9]{12}'
      minLength: 12
      maxLength: 12
    Long:
      type: integer
    PolicyRevision:
      type: string
      pattern: \S+
      minLength: 1
      maxLength: 100
    Integer:
      type: integer
    ResourcePolicy:
      type: object
      properties:
        resourceArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: ' The ARN of the resource associated with the resource policy '
        revision:
          allOf:
          - $ref: '#/components/schemas/PolicyRevision'
          - description: ' The current revision of the resource policy. '
        document:
          allOf:
          - $ref: '#/components/schemas/PolicyDocument'
          - description: ' The resource policy formatted in JSON. '
      description: ' An CodeArtifact resource policy that contains a resource ARN, document details, and a revision. '
    PaginationToken:
      type: string
      pattern: \S+
      minLength: 1
      maxLength: 2000
    DeleteDomainPermissionsPolicyResult:
      type: object
      properties:
        policy:
          allOf:
          - $ref: '#/components/schemas/ResourcePolicy'
          - description: ' Information about the deleted resource policy after processing the request. '
    RepositorySummary:
      type: object
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/RepositoryName'
          - description: ' The name of the repository. '
        administratorAccount:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: ' The Amazon Web Services account ID that manages the repository. '
        domainName:
          allOf:
          - $ref: '#/components/schemas/DomainName'
          - description: ' The name of the domain that contains the repository. '
        domainOwner:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: ' The 12-digit account number of the Amazon Web Services account that owns the domain. It does not include dashes or spaces. '
        arn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: ' The ARN of the repository. '
        description:
          allOf:
          - $ref: '#/components/schemas/Description'
          - description: ' The description of the repository. '
        createdTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: A timestamp that represents the date and time the repository was created.
      description: ' Details about a repository, including its Amazon Resource Name (ARN), description, and domain information. The <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_ListRepositories.html">ListRepositories</a> operation returns a list of <code>RepositorySummary</code> objects. '
    DescribeDomainResult:
      type: object
      properties:
        domain:
          $ref: '#/components/schemas/DomainDescription'
    ListRepositoriesInDomainResult:
      type: object
      properties:
        repositories:
          allOf:
          - $ref: '#/components/schemas/RepositorySummaryList'
          - description: ' The returned list of repositories. '
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: ' If there are additional results, this is the token for the next set of results. '
    AccessDeniedException: {}
    CreateDomainResult:
      type: object
      properties:
        domain:
          allOf:
          - $ref: '#/components/schemas/DomainDescription'
          - description: ' Contains information about the created domain after processing the request. '
    RepositorySummaryList:
      type: array
      items:
        $ref: '#/components/schemas/RepositorySummary'
    TagKey:
      type: string
      pattern: \P{C}+
      minLength: 1
      maxLength: 128
    Timestamp:
      type: string
      format: date-time
    PolicyDocument:
      type: string
      pattern: '[\P{C}\s]+'
      minLength: 1
      maxLength: 7168
    RepositoryName:
      type: string
      pattern: '[A-Za-z0-9][A-Za-z0-9._\-]{1,99}'
      minLength: 2
      maxLength: 100
    Tag:
      type: object
      required:
      - key
      - value
      properties:
        key:
          allOf:
          - $ref: '#/components/schemas/TagKey'
          - description: The tag key.
        value:
          allOf:
          - $ref: '#/components/schemas/TagValue'
          - description: The tag value.
      description: A tag is a key-value pair that can be used to manage, search for, or filter resources in CodeArtifact.
    DomainDescription:
      type: object
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/DomainName'
          - description: ' The name of the domain. '
        owner:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: ' The Amazon Web Services account ID that owns the domain. '
        arn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: ' The Amazon Resource Name (ARN) of the domain. '
        status:
          allOf:
          - $ref: '#/components/schemas/DomainStatus'
          - description: ' The current status of a domain. '
        createdTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: ' A timestamp that represents the date and time the domain was created. '
        encryptionKey:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: ' The ARN of an Key Management Service (KMS) key associated with a domain. '
        repositoryCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: ' The number of repositories in the domain. '
        assetSizeBytes:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: ' The total size of all assets in the domain. '
        s3BucketArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the Amazon S3 bucket that is used to store package assets in the domain.
      description: ' Information about a domain. A domain is a container for repositories. When you create a domain, it is empty until you add one or more repositories. '
    Arn:
      type: string
      pattern: \S+
      minLength: 1
      maxLength: 1011
    DeleteDomainResult:
      type: object
      properties:
        domain:
          allOf:
          - $ref: '#/components/schemas/DomainDescription'
          - description: ' Contains information about the deleted domain after processing the request. '
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codeartifact/
x-hasEquivalentPaths: true
